### ISSUE TITLE
Does this action honor a `.flake8` config file in the repo?

### ISSUE THREAD

**Issue by ericdrosas87** [mhitza/flake8-jupyter-notebook#5]
It seems to, but it's not clear to me. If it does can the `README.md` be updated?

**Comment by mhitza** [comment]
If flake8 picks those up when started, then it should, as flake8 is spawned in the root of the repository with a single custom flag (`exit-code`) https://github.com/mhitza/flake8-jupyter-notebook/blob/master/annotate#L55

Do note that the bundled flake8 is a rather old version (~2 years old) and would be worth testing it out and reporting back, in case I should update the README or build a newer action version.

**Comment by ericdrosas87** [comment]
> Do note that the bundled flake8 is a rather old version (~2 years old) and would be worth testing it out and reporting back, in case I should update the README or build a newer action version.

That was going to be another question of mine: So this project is still being maintained?

**Comment by mhitza** [comment]
It is indeed maintained. While I don't use this action anymore, I'm happy to fix any bugs and update with useful features as time permits.

**Comment by ericdrosas87** [comment]
So it looks like the config file is picked up, but only some of the options are adhered to. For example, my config file:

```
[flake8]
max-line-length = 99
exclude = experimental_notebooks
ignore = E133, E226, E228, E266, N802, N803, N806, N812, N813, N815, N816, W503
```

The `exclude` property is currently ignored by the action. Are you open to considering a feature request to ensure that the `exclude` property is adhered to?

**Comment by mhitza** [comment]
I have pushed a new release of the action which version 7.0.0 of flake8. In the [release notes for versions up to 7.0.0](https://flake8.pycqa.org/en/latest/release-notes/index.html) (previously 5.0.4) I saw no mention of configuration changes, or new features that might relate to the exclude option. Maybe give it a spin and see if this updated version works as expected.

**Comment by ericdrosas87** [comment]
@mhitza I tested out the new version of the Action and unfortunately it looks like it's still not picking up the excluded folder, even when I explicitly list out each notebook within the folder

**Comment by mhitza** [comment]
Updated the readme with the supported configuration options. In order to ignore certain files/paths from checks you would need to use the new `ignore` input option (example in README). There are a few more notes in the linked PR.
